market_type: spot
time_start: "20230701"
time_end: "20250101"
pairs: ['ETH/USDT']
run_policy:
  - name: ma:demo
    run_timeframes: [15m]
    # pairs: [BTC/USDT:USDT]
    params: {atr: 15}
accounts:
  user1:
    binance:
      prod:
        api_key: vvv
        api_secret: vvv
